/*
 * Muestra un Fractal que asemeja un Arbol
 *
 */
package com.manager;

import com.manager.fractals.IFractal;
import java.awt.Canvas;
import javax.swing.JFrame;

/**
 * Una ventana Modal, que muestra un Arbol fractal
 *
 * @author manager
 */
public class dlgTree extends javax.swing.JDialog {

    /**
     * Creates new form dlgTree
     *
     * @param parent
     * @param canvas
     */
    public dlgTree(JFrame parent, Canvas canvas) {
        super(parent, true);
        initComponents();

//        pnlGraph.getLayout().addLayoutComponent("Canvas", new CanvasFractalTree());
//        javax.swing.JButton jButton = new javax.swing.JButton();
//        jButton.setText("TEST");
//        jButton.setFocusable(false);
//        jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton.setMaximumSize(new java.awt.Dimension(65, 30));
//        jButton.setMinimumSize(new java.awt.Dimension(65, 30));
//        jButton.setPreferredSize(new java.awt.Dimension(65, 30));
//        jButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//
//        pnlGraph.add(jButton, java.awt.BorderLayout.PAGE_START);
        pnlGraph.add(canvas, java.awt.BorderLayout.CENTER);
        ((IFractal) canvas).setup(pnlGraph);

//        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane();
//        javax.swing.JPanel panel = new javax.swing.JPanel();
//
//        panel.setMaximumSize(new java.awt.Dimension(1000, 1000));
//        panel.setMinimumSize(new java.awt.Dimension(1000, 1000));
//        panel.setPreferredSize(new java.awt.Dimension(1000, 1000));
//        panel.setLayout(new java.awt.BorderLayout());
//        panel.add(new CanvasFractalTree(), java.awt.BorderLayout.CENTER);
//
//        scroll.setViewportView(panel);
//
//        pnlGraph.add(scroll, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pnlGraph = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(1000, 25));
        jToolBar1.setMinimumSize(new java.awt.Dimension(100, 25));

        jButton1.setText("RUN");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(filler1);

        jButton2.setText("Char -");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Char +");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(filler2);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setText("Vel -");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setText("Vel +");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(filler3);

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setText("Color -");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setText("Color +");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(65, 30));
        jButton7.setMinimumSize(new java.awt.Dimension(65, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(65, 30));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        getContentPane().add(jToolBar1);

        pnlGraph.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlGraph);

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlGraph;
    // End of variables declaration//GEN-END:variables

}
