/*
 * Muestra un Fractal que asemeja un Arbol
 *
 */
package com.manager;

import com.manager.fractals.CanvasFractalModel;
import javax.swing.JFrame;

/**
 * Una ventana Modal, que muestra un Arbol fractal
 *
 * @author manager
 */
public class dlgTree extends javax.swing.JDialog {

    final CanvasFractalModel canvas;

    /**
     * Creates new form dlgTree
     *
     * @param parent
     * @param canvas
     */
    public dlgTree(JFrame parent, CanvasFractalModel canvas) {
        super(parent, true);
        initComponents();

        this.canvas = canvas;

        pnlGraph.add(this.canvas, java.awt.BorderLayout.CENTER);
        this.canvas.Setup(pnlGraph);
        lblVel.setText(String.valueOf(100 - CanvasFractalModel.getTpause()));
        lblAng.setText(String.valueOf(CanvasFractalModel.getInitAngle()));
        lblDeep.setText(String.valueOf(CanvasFractalModel.getInitDeep()));
    }

    /**
     * A los fines de ejecutar las acciones cuando se muestre el dialogo
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);

        if (b) {
            canvas.Clear();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnClear = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        btnRun = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        btnVelMenos = new javax.swing.JButton();
        lblVel = new javax.swing.JLabel();
        btnVelMas = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        btnAnguloMenos = new javax.swing.JButton();
        lblAng = new javax.swing.JLabel();
        btnAnguloMas = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        mnuDeepMenos = new javax.swing.JButton();
        lblDeep = new javax.swing.JLabel();
        mnuDeepMas = new javax.swing.JButton();
        pnlGraph = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(1000, 25));
        jToolBar1.setMinimumSize(new java.awt.Dimension(100, 25));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setText("CLEAR");
        btnClear.setFocusable(false);
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setMaximumSize(new java.awt.Dimension(65, 30));
        btnClear.setMinimumSize(new java.awt.Dimension(65, 30));
        btnClear.setPreferredSize(new java.awt.Dimension(65, 30));
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClear);
        jToolBar1.add(filler4);

        btnRun.setBackground(new java.awt.Color(0, 102, 0));
        btnRun.setText("RUN");
        btnRun.setFocusable(false);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRun.setMaximumSize(new java.awt.Dimension(65, 30));
        btnRun.setMinimumSize(new java.awt.Dimension(65, 30));
        btnRun.setPreferredSize(new java.awt.Dimension(65, 30));
        btnRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRun);
        jToolBar1.add(filler1);

        btnVelMenos.setBackground(new java.awt.Color(153, 153, 255));
        btnVelMenos.setText("Vel -");
        btnVelMenos.setFocusable(false);
        btnVelMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVelMenos.setMaximumSize(new java.awt.Dimension(65, 30));
        btnVelMenos.setMinimumSize(new java.awt.Dimension(65, 30));
        btnVelMenos.setPreferredSize(new java.awt.Dimension(65, 30));
        btnVelMenos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVelMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelMenosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVelMenos);

        lblVel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblVel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVel.setMaximumSize(new java.awt.Dimension(30, 30));
        lblVel.setMinimumSize(new java.awt.Dimension(30, 30));
        lblVel.setPreferredSize(new java.awt.Dimension(30, 30));
        jToolBar1.add(lblVel);

        btnVelMas.setBackground(new java.awt.Color(153, 153, 255));
        btnVelMas.setText("Vel +");
        btnVelMas.setFocusable(false);
        btnVelMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVelMas.setMaximumSize(new java.awt.Dimension(65, 30));
        btnVelMas.setMinimumSize(new java.awt.Dimension(65, 30));
        btnVelMas.setPreferredSize(new java.awt.Dimension(65, 30));
        btnVelMas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVelMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelMasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVelMas);
        jToolBar1.add(filler3);

        btnAnguloMenos.setBackground(new java.awt.Color(51, 51, 255));
        btnAnguloMenos.setText("Angulo -");
        btnAnguloMenos.setFocusable(false);
        btnAnguloMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnguloMenos.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAnguloMenos.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAnguloMenos.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAnguloMenos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnguloMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnguloMenosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnguloMenos);

        lblAng.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAng.setMaximumSize(new java.awt.Dimension(35, 30));
        lblAng.setMinimumSize(new java.awt.Dimension(35, 30));
        lblAng.setPreferredSize(new java.awt.Dimension(35, 30));
        jToolBar1.add(lblAng);

        btnAnguloMas.setBackground(new java.awt.Color(51, 51, 255));
        btnAnguloMas.setText("Angulo +");
        btnAnguloMas.setFocusable(false);
        btnAnguloMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnguloMas.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAnguloMas.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAnguloMas.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAnguloMas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnguloMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnguloMasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnguloMas);
        jToolBar1.add(filler5);

        mnuDeepMenos.setBackground(new java.awt.Color(102, 255, 102));
        mnuDeepMenos.setText("Deep -");
        mnuDeepMenos.setFocusable(false);
        mnuDeepMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuDeepMenos.setMaximumSize(new java.awt.Dimension(75, 30));
        mnuDeepMenos.setMinimumSize(new java.awt.Dimension(75, 30));
        mnuDeepMenos.setPreferredSize(new java.awt.Dimension(75, 30));
        mnuDeepMenos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuDeepMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeepMenosActionPerformed(evt);
            }
        });
        jToolBar1.add(mnuDeepMenos);

        lblDeep.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDeep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeep.setMaximumSize(new java.awt.Dimension(20, 30));
        lblDeep.setMinimumSize(new java.awt.Dimension(20, 30));
        lblDeep.setPreferredSize(new java.awt.Dimension(20, 30));
        jToolBar1.add(lblDeep);

        mnuDeepMas.setBackground(new java.awt.Color(102, 255, 102));
        mnuDeepMas.setText("Deep +");
        mnuDeepMas.setFocusable(false);
        mnuDeepMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuDeepMas.setMaximumSize(new java.awt.Dimension(75, 30));
        mnuDeepMas.setMinimumSize(new java.awt.Dimension(75, 30));
        mnuDeepMas.setPreferredSize(new java.awt.Dimension(75, 30));
        mnuDeepMas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuDeepMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeepMasActionPerformed(evt);
            }
        });
        jToolBar1.add(mnuDeepMas);

        getContentPane().add(jToolBar1);

        pnlGraph.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlGraph);

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        lblVel.setText(String.valueOf(CanvasFractalModel.getMAX_DEEP() - CanvasFractalModel.getTpause()));
        lblAng.setText(String.valueOf(CanvasFractalModel.getInitAngle()));
        lblDeep.setText(String.valueOf(CanvasFractalModel.getInitDeep()));
        canvas.repaint();
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnVelMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelMenosActionPerformed
        canvas.SetVelMenos();
        lblVel.setText(String.valueOf(CanvasFractalModel.getMAX_DEEP() - CanvasFractalModel.getTpause()));
    }//GEN-LAST:event_btnVelMenosActionPerformed

    private void btnVelMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelMasActionPerformed
        canvas.SetVelMas();
        lblVel.setText(String.valueOf(CanvasFractalModel.getMAX_DEEP() - CanvasFractalModel.getTpause()));
    }//GEN-LAST:event_btnVelMasActionPerformed

    private void btnAnguloMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnguloMenosActionPerformed
        canvas.SetAngMenos();
        lblAng.setText(String.valueOf(CanvasFractalModel.getInitAngle()));
    }//GEN-LAST:event_btnAnguloMenosActionPerformed

    private void btnAnguloMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnguloMasActionPerformed
        canvas.SetAngMas();
        lblAng.setText(String.valueOf(CanvasFractalModel.getInitAngle()));
    }//GEN-LAST:event_btnAnguloMasActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        canvas.setClear(true);
        lblVel.setText(String.valueOf(CanvasFractalModel.getMAX_DEEP() - CanvasFractalModel.getTpause()));
        lblAng.setText(String.valueOf(CanvasFractalModel.getInitAngle()));
        lblDeep.setText(String.valueOf(CanvasFractalModel.getInitDeep()));
        canvas.repaint();
    }//GEN-LAST:event_btnClearActionPerformed

    private void mnuDeepMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeepMenosActionPerformed
        canvas.SetDeepMenos();
        lblDeep.setText(String.valueOf(CanvasFractalModel.getInitDeep()));
    }//GEN-LAST:event_mnuDeepMenosActionPerformed

    private void mnuDeepMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeepMasActionPerformed
        canvas.SetDeepMas();
        lblDeep.setText(String.valueOf(CanvasFractalModel.getInitDeep()));
    }//GEN-LAST:event_mnuDeepMasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnguloMas;
    private javax.swing.JButton btnAnguloMenos;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnVelMas;
    private javax.swing.JButton btnVelMenos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAng;
    private javax.swing.JLabel lblDeep;
    private javax.swing.JLabel lblVel;
    private javax.swing.JButton mnuDeepMas;
    private javax.swing.JButton mnuDeepMenos;
    private javax.swing.JPanel pnlGraph;
    // End of variables declaration//GEN-END:variables

}
