package com.manager.menu_actions;

/**
 * Ventana que muestra informacion basica de la aplicacion
 *
 * @author manager
 */
public class dlgAcercaDe extends javax.swing.JDialog {

    /**
     * Ventana Modal
     *
     * Creates new form dlgAcercaDe
     *
     * @param parent
     */
    public dlgAcercaDe(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Fractal");
        setBackground(new java.awt.Color(0, 51, 153));
        setForeground(new java.awt.Color(0, 51, 153));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setAlignmentX(0.5F);
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 25));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 25));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNIVERSIDAD TECNOLÓGICA DE LA HUASTECA HIDALGUENSE");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 25));
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 102, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\nNOMBRE: KEVIN FRANCISCO MINA MARTÍNEZ\nMATRICULA: 20200967\nCARRERA: TECNOLOGÍAS DE LA INFORMACIÓN \nCUATRIMESTRE: 4TO\nGRUPO: C\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        setSize(new java.awt.Dimension(610, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
